### ISSUE TITLE
Chart window covers marker detail view

### ISSUE THREAD

**Issue by tamberg** [mitwelten/mitwelten-discover-app#1]
If a marker in the lower half of the screen is selected, the marker detail view opens (as expected), then the chart window opens (as expected) and covers up the marker detail view. Consider moving the marker to the new center of the remaining map view.

<img width="1552" alt="Screenshot 2023-08-31 at 15 46 12" src="https://github.com/mitwelten/mitwelten-discover-app/assets/142092/3ed2a2b4-2507-48f6-b209-6918aa3a0321">
<img width="1552" alt="Screenshot 2023-08-31 at 15 46 02" src="https://github.com/mitwelten/mitwelten-discover-app/assets/142092/d4d7c0b1-49dc-40f5-bcc1-d7c7007fd311">

**Comment by AndriWild** [comment]
This issue has been fixed in the latest map handling update.
